customhost = "employee.c96tzl5ybe99.us-east-1.rds.amazonaws.com"
customuser = "aws_employee"
custompass = "employeepassword"
customdb = "employee"
custombucket = "foowengchuen-employee"
customregion = "us-east-1"
